#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TimeSerie": "00_preprocessing.ipynb",
         "TestTimeSerie": "00_preprocessing.ipynb"}

modules = ["preprocessing.py"]

git_url = "https://github.com/rubens36/deepwave/tree/master/"

def custom_doc_links(name): return None