# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"check_files": "00_preprocessing.ipynb",
         "Labels": "00_preprocessing.ipynb",
         "get_freq_from_file": "00_preprocessing.ipynb",
         "change_data_frequency": "00_preprocessing.ipynb",
         "split_data": "00_preprocessing.ipynb",
         "load_data_one_file": "00_preprocessing.ipynb",
         "load_data_list": "00_preprocessing.ipynb",
         "load_data_folder": "00_preprocessing.ipynb",
         "plot_data": "00_preprocessing.ipynb",
         "__binary_search": "00_preprocessing.ipynb",
         "binary_search": "00_preprocessing.ipynb",
         "get_window_range": "00_preprocessing.ipynb",
         "plot_window": "00_preprocessing.ipynb",
         "plot_all_windows": "00_preprocessing.ipynb",
         "TimeSerie": "00_preprocessing.ipynb",
         "TestTimeSerie": "00_preprocessing.ipynb"}

modules = ["preprocessing.py"]

doc_url = "https://rubens36.github.io/deepwave/"

git_url = "https://github.com/rubens36/deepwave/tree/master/"

def custom_doc_links(name): return None